breach2.o: breach2.c breach2.h
   cc breach2 -Z3400 +d
   
breach20.o: breach20.c breach2.h
   cc breach20 +d
   
breach22.o: breach22.c breach2.h
   cc breach22 +d
   
breach23.o: breach23.c breach2.h
   cc breach23 +d
   
breach24.o: breach24.c breach2.h
   cc breach24 +d
   
breach25.o: breach25.c breach2s.h
   cc -E200 breach25 +d
   
breach26.o: breach26.c breach2.h
   cc breach26 +d
   
breach27.o: breach27.c breach2.h
   cc breach27 +d
   
breach28.o: breach28.c breach2.h
   cc breach28 +d
   
breach29.o: breach29.c breach2s.h
   cc -E200 breach29 +d
   
breach2b.o: breach2b.c breach2.h
   cc breach2b +d
   
breach2a.o: breach2a.c breach2.h
   cc breach2a +d
   
breach2c.o: breach2c.c breach2.h
   cc breach2c +d
   
breach2d.o: breach2d.c breach2.h
   cc breach2d +d
   
breach2: breach20.o breach2.o breach22.o breach23.o breach24.o breach25.o breach26.o breach27.o breach28.o breach29.o breach2a.o breach2b.o breach2c.o breach2d.o
   ln breach2 breach20 breach22 breach23 breach24 breach25 breach26 breach27 breach28 breach29 breach2a breach2b breach2c breach2d -lc
